spring.application.name=Find-A-Dice-Thymeleaf

#TODO To Add MAP_UPLOAD_DIR here as app.upload.map-dir with @Value

#Data Source Properties
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

#JPA Properties

spring.data.jdbc.dialect=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql = false
spring.jpa.properties.hibernate.format_sql = false

#Logging Levels
logging.level.org = WARN
logging.level.blog = WARN
logging.file.name=log/logger.log

#Show SQL
logging.level.org.hibernate.sql = WARN
logging.level.org.hibernate.type.descriptor = WARN
