package io.ethertale.findadicethymeleaf.hero.model;

public enum Races {
    AARAKOCRA,
    AASIMAR,
    AETHERBORN,
    AIR_GENASI,
    ASTRAL_ELF,
    AUTOGNOME,
    AVEN,
    BUGBEAR,
    CENTAUR,
    CHANGELING,
    DRAGONBORN,
    DWARF,
    ELF_DROW,
    ELF_HIGH,
    ELF_WOOD,
    FIRBOLG,
    FAIRY,
    FIRE_GENASI,
    GALLED,
    GILLIAN,
    GITHYANKI,
    GITHZERAI,
    GNOME,
    GOBLIN,
    GOLIATH,
    GRIFFONBORN,
    GRUNG,
    HADOZEE,
    HALF_ELF,
    HALF_ORC,
    HALFLING,
    HARRENGON,
    HAVERFORD,
    HOBGOBLIN,
    HUMAN,
    IZZET,
    KALASHTAR,
    KENDER,
    KOBOLD,
    KOORD,
    LIZARDFOLK,
    LOXODON,
    MINOTAUR,
    ORC,
    PLASMOID,
    RATKIN,
    SHIFTER_BEASORT,
    SHIFTER_LONGTOOTH,
    SHIFTER_RAZORCLAW,
    SHIFTER_WINGED,
    SIMIC_HYBRID,
    TABAXI,
    TORTLE,
    TRITON,
    VARIANT_HUMAN,
    VEDALKEN,
    WARFORGED,
    WATER_GENASI;

    @Override
    public String toString() {
        return name()
                .replace("_", " ");
    }
}
